
- image-color: projects/citesphere-logo.png
  image-white: projects/citesphere-white.png
  url: projects/app-pages/citesphere
  id: citesphere-img-1
  name: Citesphere
  description: "Manage your citations and more."

- image-color: projects/conceptpower-logo.png
  image-white: projects/conceptpower-white.png
  url: projects/app-pages/conceptpower
  id: conceptpower-img-1
  name: Conceptpower
  description: "Search for concepts and related words."

- image-color: projects/vspace-logo.png
  image-white: projects/virtualspaces-white.png
  url: projects/app-pages/virtualspaces
  id: virtualspaces-img-1
  name: Virtual Spaces 2.0
  description: "Build virtual exhibitions through 2D space."

- image-color: projects/vogonweb-logo.png
  image-white: projects/vogonweb-white.png
  url: projects/app-pages/vogonweb
  id: vogonweb-img-1
  name: VogonWeb
  description: "Annotate texts and create networks."

- image-color: projects/giles-logo.png
  image-white: projects/giles-white.png
  url: projects/app-pages/giles
  id: giles-img-1
  name: Giles
  description: "Extract text and images from documents."

- image-color: projects/Quadriga-logo.png
  image-white: projects/Quadriga-logo.png
  url: projects/app-pages/quadriga
  id: quadriga-img-1
  name: Quadriga
  description: "View and manange annotated networks."
